spring:
  cloud:
    gateway:
      routes:
        - id: chords-service
          uri: http://localhost:8211
          predicates:
            - Path=/chords/api/v**/**
          filters:
            - StripPrefix=1
        - id: notifications-service
          uri: http://localhost:8311
          predicates:
            - Path=/notifications/api/v**/**
          filters:
            - StripPrefix=1

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
