/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Chord } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ChordsApiServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List all chords
     * Retrieves a list of all guitar chords available in the system.
     */
    listChords(extraHttpRequestParams?: any): Observable<Array<Chord>>;

}
