/**
 * Guitara Chords Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DefaultChord } from '../model/models';
import { DefaultChordNoIdDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ChordsDefaultAPIServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a default chord
     * Creates a new default chord in the system. Only accessible by users with ADMIN authority.
     * @param defaultChordNoIdDto 
     */
    createDefaultChord(defaultChordNoIdDto: DefaultChordNoIdDto, extraHttpRequestParams?: any): Observable<DefaultChord>;

    /**
     * Get default chord available group names
     * Retrieves all default chord group names available.
     */
    getDefaultChordGroupsNames(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Get default chords of a specific group
     * Retrieves all default chords belonging to a specific group.
     * @param group 
     */
    getDefaultChordsOfGroup(group: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G', extraHttpRequestParams?: any): Observable<Array<DefaultChord>>;

    /**
     * List all chords
     * Retrieves a list of all guitar chords available in the system.
     */
    listChords(extraHttpRequestParams?: any): Observable<{ [key: string]: Array<DefaultChord>; }>;

}
