/**
 * Guitara Chords Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Chord } from '../model/models';
import { ChordNoIdDto } from '../model/models';
import { SimpleErrorResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ChordsUserAPIServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create a new chord for the user
     * Allows the authenticated user to create a new guitar chord.
     * @param chordNoIdDto 
     */
    createUserChord(chordNoIdDto: ChordNoIdDto, extraHttpRequestParams?: any): Observable<Chord>;

    /**
     * Delete a user chord
     * Allows the authenticated user to delete a specific chord by its ID.
     * @param id 
     */
    deleteUserChord(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get all user chords
     * Retrieves a list of guitar chords specific to the authenticated user.
     */
    getUserChords(extraHttpRequestParams?: any): Observable<Array<Chord>>;

    /**
     * Update a user chord
     * Allows the authenticated user to update an existing chord by its ID.
     * @param id 
     * @param chordNoIdDto 
     */
    updateUserChord(id: string, chordNoIdDto: ChordNoIdDto, extraHttpRequestParams?: any): Observable<{}>;

}
