spring:
  application:
    name: config-server
  main:
    banner-mode: off
  profiles:
    default: dev
  threads:
    virtual:
      enabled: true
  cloud:
    config:
        server:
          git:
            uri: https://github.com/edweo/guitara-config-repo
            clone-on-start: true
            skip-ssl-validation: true
  security:
    user:
      name: root
      password: secret