/**
 * Guitara Chords Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Chord } from './chord';


export interface DefaultChord { 
    id?: string;
    chord?: Chord;
    group?: DefaultChord.GroupEnum;
}
export namespace DefaultChord {
    export const GroupEnum = {
        A: 'A',
        B: 'B',
        C: 'C',
        D: 'D',
        E: 'E',
        F: 'F',
        G: 'G'
    } as const;
    export type GroupEnum = typeof GroupEnum[keyof typeof GroupEnum];
}


