/**
 * Guitara Chords Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChordNoIdDto } from './chordNoIdDto';


export interface DefaultChordNoIdDto { 
    group?: DefaultChordNoIdDto.GroupEnum;
    chord?: ChordNoIdDto;
}
export namespace DefaultChordNoIdDto {
    export const GroupEnum = {
        A: 'A',
        B: 'B',
        C: 'C',
        D: 'D',
        E: 'E',
        F: 'F',
        G: 'G'
    } as const;
    export type GroupEnum = typeof GroupEnum[keyof typeof GroupEnum];
}


