version: '3.9'
name: 'guitara'

services:
  chords-service-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - '5133:5432'
    volumes:
      - chords-service-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: chords_db

volumes:
  chords-service-db:
    driver: local