version: '3.9'
name: 'guitara'

services:
  chords-service-db:
    image: postgres:14.18
    restart: always
    shm_size: 128mb
    ports:
      - '5133:5432'
    volumes:
      - chords-service-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: chords_db

  keycloak-db:
    image: postgres:14.18
    restart: always
    shm_size: 128mb
    ports:
      - '5233:5432'
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: keycloak_db

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    restart: always
    ports:
      - '7555:8080'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    depends_on:
      - keycloak-db
    command:
      - start-dev

  # Observability

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ../observability/prometheus:/etc/prometheus
      - prometheus-storage:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus-dev.yml"

volumes:
  chords-service-db:
    driver: local
  keycloak-db:
    driver: local
  grafana-storage:
    driver: local
  prometheus-storage:
    driver: local