spring:
  application:
    name: notifications-service
  main:
      banner-mode: off
  threads:
    virtual:
      enabled: true
  profiles:
      default: dev
  config:
    import: configserver:http://root:secret@localhost:7777