spring:
  application:
    name: chords-service
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui.path: /swagger-ui
  api-docs.path: /api-docs
  show-actuator: true
  packages-to-scan: org.guitara.chordsservice